version: '3.9'
services:
  clock:
    build:
      context: ./services/clock
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/clock/src:/app/src
      - ./services/clock/package.json:/app/package.json
      - ./services/clock/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    networks:
      - clock
      - rabbitmq
    depends_on:
      clock-mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mail:
    build:
      context: ./services/mail
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/mail/src:/app/src
      - ./services/mail/package.json:/app/package.json
      - ./services/mail/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    networks:
      - mail
      - rabbitmq
    depends_on:    
      mail-mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  read:
    build:
      context: ./services/read
      dockerfile: Dockerfile.dev
    ports:
      - "5003:5003"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/read/src:/app/src
      - ./services/read/package.json:/app/package.json
      - ./services/read/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    networks:
      - read
      - rabbitmq
    depends_on:
      - read-mongodb
      - rabbitmq   

  register:
    build:
      context: ./services/register
      dockerfile: Dockerfile.dev
    ports:
      - "5004:5004"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/register/src:/app/src
      - ./services/register/package.json:/app/package.json
      - ./services/register/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    networks:
      - register
      - rabbitmq
    depends_on:
      - register-mongodb
      - rabbitmq   

  score:
    build:
      context: ./services/score
      dockerfile: Dockerfile.dev
    ports:
      - "5005:5005"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/score/src:/app/src
      - ./services/score/package.json:/app/package.json
      - ./services/score/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    networks:
      - score
      - rabbitmq
    depends_on:
      - score-mongodb
      - rabbitmq    

  target:
    build:
      context: ./services/target
      dockerfile: Dockerfile.dev
    ports:
      - "5006:5006"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    env_file:
      - .env  
    volumes:
      - ./services/target/src:/app/src
      - ./services/target/package.json:/app/package.json
      - ./services/target/package-lock.json:/app/package-lock.json
    networks:
      - target
      - rabbitmq
    depends_on:
      - target-mongodb
      - rabbitmq   
  
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    ports:
      - "5007:5007"
    volumes:
      - ./services/auth/src:/app/src
      - ./services/auth/package.json:/app/package.json
      - ./services/auth/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    networks:
      - auth
      - rabbitmq
    depends_on:
      auth-mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4.0.7
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always
    networks:
      - rabbitmq
    attach: false

  auth-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_AUTH_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_AUTH_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_AUTH_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/auth-mongodb/data:/data/db
    networks:
      - auth

  mail-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_MAIL_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_MAIL_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_MAIL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/mail-mongodb/data:/data/db
    networks:
      - mail

  clock-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_CLOCK_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_CLOCK_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_CLOCK_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/clock-mongodb/data:/data/db
    networks:
      - clock

  read-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_READ_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_READ_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_READ_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/read-mongodb/data:/data/db
    networks:
      - read

  register-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_REGISTER_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_REGISTER_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_REGISTER_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/register-mongodb/data:/data/db
    networks:
      - register


  score-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_SCORE_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_SCORE_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_SCORE_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/score-mongodb/data:/data/db
    networks:
      - score

  target-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_TARGET_PORT}:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_TARGET_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_TARGET_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/target-mongodb/data:/data/db
    networks:
      - target

networks:
  auth:
    driver: bridge
  mail:
    driver: bridge
  clock:
    driver: bridge
  rabbitmq:
    driver: bridge
  read:
    driver: bridge
  register:
    driver: bridge  
  score:
    driver: bridge
  target:
    driver: bridge
