services:
  clock:
    build:
      context: ./services/clock
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/clock/src:/app/src
      - ./services/clock/package.json:/app/package.json
      - ./services/clock/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - rabbitmq  
    networks:

  mail:
    build:
      context: ./services/mail
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/mail/src:/app/src
      - ./services/mail/package.json:/app/package.json
      - ./services/mail/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - rabbitmq  
      - mail-mongodb
    networks:
      - rabbitmq
      - mail

  read:
    build:
      context: ./services/read
      dockerfile: Dockerfile.dev
    ports:
      - "5003:5003"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/read/src:/app/src
      - ./services/read/package.json:/app/package.json
      - ./services/read/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - rabbitmq  
    networks:

  register:
    build:
      context: ./services/register
      dockerfile: Dockerfile.dev
    ports:
      - "5004:5004"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/register/src:/app/src
      - ./services/register/package.json:/app/package.json
      - ./services/register/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - rabbitmq  
    networks:

  score:
    build:
      context: ./services/score
      dockerfile: Dockerfile.dev
    ports:
      - "5005:5005"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./services/score/src:/app/src
      - ./services/score/package.json:/app/package.json
      - ./services/score/package-lock.json:/app/package-lock.json
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - rabbitmq  
    networks:

  target:
    build:
      context: ./services/target
      dockerfile: Dockerfile.dev
    ports:
      - "5006:5006"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    env_file:
      - .env
    networks:
      - rabbitmq
    depends_on:
      - rabbitmq      
    volumes:
      - ./services/target/src:/app/src
      - ./services/target/package.json:/app/package.json
      - ./services/target/package-lock.json:/app/package-lock.json
  
  rabbitmq:
    image: rabbitmq:4.0.7
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always
    networks:
      - rabbitmq
    attach: false

  auth-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_AUTH_PORT}:${MONGO_AUTH_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_AUTH_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_AUTH_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/auth-mongodb/data:/data/db
    networks:
      - auth

  mail-mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_MAIL_PORT}:${MONGO_MAIL_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_MAIL_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_MAIL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - /docker/mail-mongodb/data:/data/db
    networks:
      - mail


networks:
  auth:
    driver: bridge
  mail:
    driver: bridge
  rabbitmq:
    driver: bridge
