services:
  clock:
    build:
      context: ./services/clock
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./services/clock/src:/app/services/clock/src
      - ./services/clock/package.json:/app/services/clock/package.json
      - ./services/clock/package-lock.json:/app/services/clock/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network
  mail:
    build:
      context: ./services/mail
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    volumes:
      - ./services/mail/src:/app/services/mail/src
      - ./services/mail/package.json:/app/services/mail/package.json
      - ./services/mail/package-lock.json:/app/services/mail/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network

  read:
    build:
      context: ./services/read
      dockerfile: Dockerfile.dev
    ports:
      - "5003:5003"
    volumes:
      - ./services/read/src:/app/services/read/src
      - ./services/read/package.json:/app/services/read/package.json
      - ./services/read/package-lock.json:/app/services/read/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network
    
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    ports:
      - "5007:5007"
    volumes:
      - ./services/auth/src:/app/services/auth/src
      - ./services/auth/package.json:/app/services/auth/package.json
      - ./services/auth/package-lock.json:/app/services/auth/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network

  register:
    build:
      context: ./services/register
      dockerfile: Dockerfile.dev
    ports:
      - "5004:5004"
    volumes:
      - ./services/register/src:/app/services/register/src
      - ./services/register/package.json:/app/services/register/package.json
      - ./services/register/package-lock.json:/app/services/register/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network

  score:
    build:
      context: ./services/score
      dockerfile: Dockerfile.dev
    ports:
      - "5005:5005"
    volumes:
      - ./services/score/src:/app/services/score/src
      - ./services/score/package.json:/app/services/score/package.json
      - ./services/score/package-lock.json:/app/services/score/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network

  target:
    build:
      context: ./services/target
      dockerfile: Dockerfile.dev
    ports:
      - "5006:5006"
    volumes:
      - ./services/target/src:/app/services/target/src
      - ./services/target/package.json:/app/services/target/package.json
      - ./services/target/package-lock.json:/app/services/target/package-lock.json
      - .env:/app/.env
    stdin_open: true
    env_file:
      - .env
    networks:
      - main-network

  mongodb:
    restart: always

    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /docker/mongodb/data:/data/db
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
