openapi: 3.0.0
info:
  title: API Gateway
  description: API Gateway for microservices
  version: 1.0.0
servers:
  - url: http://localhost:5008
    description: Local development server
paths:
  # Define your API paths here
  # For example:
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: Success
        "503":
          description: Service unavailable
  # Add more paths as needed
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
