services:
  mongodb:
    restart: always

    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=fi2idojiekgivkck2kjhi4
    volumes:
      - /docker/mongodb/data:/data/db
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
