services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5004:5004"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
    stdin_open: true
    env_file:
      - .env
